### ISSUE TITLE
stage III

### ISSUE THREAD

**Issue by rusdevops** [VladislavMashkov/HW1_03#1]
- [x] 1. Избыточная проверка https://github.com/VladislavMashkov/HW1_03/blob/a29d70c33dfa9f81830791388c34e8222fdd0ef5/include/Stack.hpp#L25
- [x] 2. Неоптимальное копирование
https://github.com/VladislavMashkov/HW1_03/blob/a29d70c33dfa9f81830791388c34e8222fdd0ef5/include/Stack.hpp#L30-L32
- [x] 3. Дублирование кода здесь
https://github.com/VladislavMashkov/HW1_03/blob/a29d70c33dfa9f81830791388c34e8222fdd0ef5/include/Stack.hpp#L46
и здесь
https://github.com/VladislavMashkov/HW1_03/blob/a29d70c33dfa9f81830791388c34e8222fdd0ef5/include/Stack.hpp#L55
- [x] 4. Тип возвращаемого значения должен быть `void`
https://github.com/VladislavMashkov/HW1_03/blob/a29d70c33dfa9f81830791388c34e8222fdd0ef5/include/Stack.hpp#L93

**Comment by VladislavMashkov** [comment]
Вячеслав Вадимович, я подправил код по третьему этапу домашнего задания Stack
